# Generated by Django 4.2 on 2023-04-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ip_adress',
            field=models.TextField(default='', max_length=40),
        ),
    ]
