# Generated by Django 4.2 on 2023-04-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_user_last_ip_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default=True),
            preserve_default=False,
        ),
    ]
