# Generated by Django 4.2 on 2023-04-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_files_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='files_view_name_format',
            field=models.CharField(default=True),
            preserve_default=False,
        ),
    ]
