# Generated by Django 4.2 on 2023-04-27 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_files_files_view_name_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
