# Generated by Django 4.2 on 2023-04-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_files_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='files_view_name_format',
        ),
    ]
