# Generated by Django 4.2 on 2023-04-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_remove_files_files_view_name_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='person/files/% Y/% m/% d/'),
        ),
    ]
